### ISSUE TITLE
SimpleAlias does not work with Spigot 1.14.4

### ISSUE THREAD

**Issue by cbronak** [DarkBlade12/SimpleAlias#6]
I recently started updating our MC-Server to 1.14.4 and SimpleAlias never had issues with past updates before. However looks like the 1.14 finaly did break the plugin.
Hope you still got some time to fix that, i really appreciate your plugin.

Using a default spigot-server with no other plugins than SimpleAlias.

Server:  **CraftBukkit version git-Spigot-798ea6a-368f4e9 (MC: 1.14.4)** (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**SimpleAlias v1.6.2**

Tested with Java 8 and Java 11, same result.

On server start:

`[09:18:50] [Server thread/WARN]: Plugin SimpleAlias v1.6.2 does not specify an api-version.
[09:18:50] [Server thread/INFO]: [SimpleAlias] Loading SimpleAlias v1.6.2`

`[09:19:14] [Server thread/INFO]: [SimpleAlias] Enabling SimpleAlias v1.6.2
[09:19:14] [Server thread/INFO]: [SimpleAlias] config.yml successfully loaded.
[09:19:14] [Server thread/ERROR]: Error occurred while enabling SimpleAlias v1.6.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at com.darkblade12.simplealias.reader.Reader.saveResourceFile(Reader.java:34) ~[?:?]
	at com.darkblade12.simplealias.reader.types.ConfigurationTemplateReader.isOutputFileReadable(ConfigurationTemplateReader.java:51) ~[?:?]
	at com.darkblade12.simplealias.reader.types.ConfigurationTemplateReader.readFromFile(ConfigurationTemplateReader.java:19) ~[?:?]
	at com.darkblade12.simplealias.reader.types.ConfigurationTemplateReader.readConfigurationTemplate(ConfigurationTemplateReader.java:33) ~[?:?]
	at com.darkblade12.simplealias.SimpleAlias.onEnable(SimpleAlias.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot.jar:git-Spigot-798ea6a-368f4e9]
	at java.lang.Thread.run(Thread.java:834) [?:?]

-->> Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot.jar:git-Spigot-798ea6a-368f4e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 14 more
`

**Comment by cbronak** [comment]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/

Spigot 1.14 Release Notes:

A Note on Libraries
The following libraries are API libraries and available to all plugins. It is intended that they are stable for each major version, and if for some reason they are updated, then it will be to a version where all public, non-beta APIs are compatible with the previous version.

Google guava: Same version as used by Vanilla (currently 21.0).
Google gson: Same version as used by Vanilla (currently 2.8.0).
SnakeYAML: Version 1.23 or compatible
Apache Commons Lang: Version 2.6 or compatible
Whilst not officially deprecated, users are advised to use Guava or shade in their own updated library such as Apache Commons Lang3.

The following libraries are deprecated libraries. They were available as an API library in a previous version, but are now only available at runtime. They will be removed in a future version.

json-simple 1.1.1
All users should migrate to Google gson.

**Comment by i9hdkill** [comment]
Here is an updated version 
https://github.com/HexagonMC/SimpleAlias
